=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/ModelUnit.dtd
<!---->
<!ELEMENT ModelUnit (Description,Inputs?,Outputs?,Initialization?,Function*, Algorithm+,Parametersets,Testsets)>
<!ATTLIST ModelUnit
  name CDATA #REQUIRED
  modelid CDATA #REQUIRED
  timestep CDATA #IMPLIED
  version CDATA #REQUIRED>

<!ELEMENT Description (Title,Authors,Institution,URI?,Reference?,Abstract)>
<!ATTLIST Description>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED
  platform CDATA #IMPLIED
  filename CDATA #IMPLIED
  function CDATA #IMPLIED>

<!ELEMENT Parametersets (Parameterset+)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset+)>
<!ATTLIST Testsets>

<!ELEMENT Function (#PCDATA)>
<!ATTLIST Function
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED
	type (internal|external) #REQUIRED
	description CDATA #IMPLIED>

<!ELEMENT Initialization (#PCDATA)>
<!ATTLIST Initialization
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED>	

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Authors (#PCDATA)>
<!ATTLIST Authors>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT Abstract (#PCDATA)>
<!ATTLIST Abstract>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  default CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  inputtype (variable|parameter) #REQUIRED
  parametercategory (constant|species|genotypic|soil|private) #IMPLIED
  variablecategory (state|rate|auxillary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Output EMPTY>
<!ATTLIST Output
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  max CDATA #REQUIRED
  min CDATA #REQUIRED
  variablecategory (state|rate|auxiliary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test+)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (InputValue*, OutputValue+)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT InputValue (#PCDATA) >
<!ATTLIST InputValue name CDATA #REQUIRED >

<!ELEMENT OutputValue (#PCDATA) >
<!ATTLIST OutputValue name CDATA #REQUIRED >
<!ATTLIST OutputValue description CDATA #IMPLIED >
<!ATTLIST OutputValue precision CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/exo/Example_Sirius_NetRadiationEquivalent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelUnit.dtd">
<ModelUnit modelid="1" name="NetRadiationEquivalentEvaporation" timestep="1" version="1.0">
    <Description>
        <Title>NetRadiationEquivalentEvaporation Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>absolutely non</Reference>
        <Abstract>Calculate Energy Balance </Abstract>
    </Description>
    <Inputs>
        <Input name="lambdaV" description="latent heat of vaporization of water" parametercategory="species" datatype="DOUBLE" default="2.454" min="0" max="10" unit="" uri="some url" inputtype="parameter"/>
        <Input name="netRadiation" description="" parametercategory="species" datatype="DOUBLE" default="1.566" min="0" max="1000" unit="MJ/m²d" uri="some url" inputtype="variable"/>
   
    </Inputs>
    <Outputs>

        <Output name="netRadiationEquivalentEvaporation" description=" " datatype="DOUBLE" min="0" max="5"  unit="g/m²d" uri="some url"/>

    	
    </Outputs>
    
    <Algorithm language=" " platform=""><![CDATA[
        
        netRadiationEquivalentEvaporation = netRadiation / lambdaV * 1000.0
  
      ]]>
     </Algorithm>    
    
     <Parametersets>
        <Parameterset name="set1" description="some values in there" >

        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="netRadiation">1.566</InputValue>
    			<OutputValue name="netRadiationEquivalentEvaporation" precision ="3">638.142</OutputValue>
	
        	</Test>

        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/phenology/crop2ml/unit.CumulTTFrom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="SQ.WheatPhenology.CumulTTFrom" name="CumulTTFrom" timestep="1" version="1.0">
    <Description>
        <Title>CumulTTFrom Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>Modeling development phase in the 
                Wheat Simulation Model SiriusQuality.
                See documentation at http://www1.clermont.inra.fr/siriusquality/?page_id=427</Reference>
        <Abstract>Calculate CumulTT </Abstract>
    </Description>
    <Inputs>
        <Input name="calendarMoments" description="List containing appearance of each stage" variablecategory="auxiliary"  datatype="STRINGLIST"  default= "['Sowing']" unit=""  inputtype = "variable"/>
		<Input name="calendarCumuls" description="list containing for each stage occured its cumulated thermal times" variablecategory="auxiliary"  datatype="DOUBLELIST" default="[0.0]" unit="°C d"  inputtype = "variable"/>
        <Input name="cumulTT" description="cumul TT at current date" datatype="DOUBLE" variablecategory="auxiliary" min="-200" max="10000" default="8" unit="°C d" inputtype = "variable"/>
      
    </Inputs>
    <Outputs>
        <Output name="cumulTTFromZC_65" description=" cumul TT from Anthesis to current date " variablecategory="auxiliary" datatype="DOUBLE" min="0" max="5000"  unit="°C d"/>
        <Output name="cumulTTFromZC_39" description=" cumul TT from FlagLeafLiguleJustVisible to current date " variablecategory="auxiliary" datatype="DOUBLE" min="0" max="5000"  unit="°C d" />
        <Output name="cumulTTFromZC_91" description=" cumul TT from EndGrainFilling to current date " variablecategory="auxiliary" datatype="DOUBLE" min="0" max="5000"  unit="°C d" />
    	
    </Outputs>
    
	<Algorithm  language="Python" platform="" filename="algo/py/CumulFrom.py" />
	<Algorithm  language="C#" platform="" filename="algo/cs/CumulFrom.cs" />
	<Algorithm  language="Java" platform="" filename="algo/java/CumulFrom.java" />
	<Algorithm  language="C++" platform="" filename="algo/cpp/CumulFrom.cpp" />
	<Algorithm  language="Fortran" platform="" filename="algo/f90/CumulFrom.f90" />
    <Algorithm  language="Cyml" platform="" filename="algo/pyx/CumulFrom.pyx" />
    <Algorithm  language="R" platform="" filename="algo/r/CumulFrom.r" />


    <Parametersets>
        <Parameterset name="wheat" description="some values in there" >
        </Parameterset>
     </Parametersets>
     <Testsets>
        <Testset name="check wheat model" parameterset = "wheat" description="some values in there" >
        	<Test name ="test_wheat1">
 				<InputValue name="calendarMoments">["Sowing", "Emergence", "FloralInitiation", "FlagLeafLiguleJustVisible", "Heading", "Anthesis"]</InputValue>
				<InputValue name="calendarCumuls">[0.0, 112.330110409888, 354.582294511779, 741.510096671757, 853.999637026622, 954.59002776961]</InputValue>
				<InputValue name="cumulTT">972.970888983105</InputValue>
				<OutputValue name="cumulTTFromZC_65" precision ="2">18.38</OutputValue>
				<OutputValue name="cumulTTFromZC_39" precision ="2">231.46</OutputValue>
				<OutputValue name="cumulTTFromZC_91" precision ="2">0</OutputValue>
        	</Test>
        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SiriusComponent/phenology/original/crop2ml/unit.PTQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Crop2ML.original.PTQ" name="PTQ" timestep="1" version="001">
    <Description>
        <Title>PTQ model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <URI></URI>
        <Reference>(&apos;&apos;,)</Reference>
        <ExtendedDescription>Calculate Photothermal Quaotient </ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="deltaTT" description="Thermal time increase of the day" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="100.0" min="0.0" default="0.0" unit="Â°C d"/>
        <Input name="listPARTTWindowForPTQ_t1" description="List of Daily PAR during TTWindowForPTQ thermal time period" inputtype="variable" variablecategory="state" datatype="DOUBLELIST" max="" min="" default="" unit="MJ m2 d"/>
        <Input name="listGAITTWindowForPTQ" description="List of daily Green Area Index in the window dedicated to average" inputtype="variable" variablecategory="state" datatype="DOUBLELIST" max="" min="" default="" unit="m2 leaf m-2 ground"/>
        <Input name="pAR" description="Daily Photosyntetically Active Radiation" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="10000.0" min="0.0" default="0.0" unit="MJ mÂ² d"/>
        <Input name="listTTShootWindowForPTQ_t1" description="List of Daily Shoot thermal time during TTWindowForPTQ thermal time period" inputtype="variable" variablecategory="state" datatype="DOUBLELIST" max="" min="" default="" unit="Â°C d"/>
        <Input name="kl" description="Exctinction Coefficient" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="50.0" min="0.0" default="0.45" unit=""/>
        <Input name="tTWindowForPTQ" description="Thermal time window in which averages are computed" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="70000.0" min="0.0" default="70.0" unit="Â°C d"/></Inputs>
    <Outputs>
        <Output name="listTTShootWindowForPTQ" description="List of Daily Shoot thermal time during TTWindowForPTQ thermal time period" datatype="DOUBLELIST" variablecategory="state" max="" min="" unit="Â°C d"/>
        <Output name="listPARTTWindowForPTQ" description="List of Daily PAR during TTWindowForPTQ thermal time period" datatype="DOUBLELIST" variablecategory="state" max="" min="" unit="MJ m2 d"/>
        <Output name="ptq" description="Photothermal quotient " datatype="DOUBLE" variablecategory="state" max="10000.0" min="0.0" unit="MJ Â°C-1 d-1 m-2)"/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/PTQ.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/phenology/crop2ml/unit.UpdatePhase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="SQ.WheatPhenology.UpdatePhase" name="UpdatePhase" timestep="1" version="1.0">
    <Description>
        <Title>UpdatePhase Model</Title>
        <Authors>Pierre MARTRE</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>Modeling development phase in the 
                Wheat Simulation Model SiriusQuality.
                See documentation at http://www1.clermont.inra.fr/siriusquality/?page_id=427</Reference>
        <Abstract><![CDATA[This strategy advances the phase and calculate the final leaf number]]>
    	</Abstract>
    </Description>
    <Inputs>
        <Input name="cumulTT" description="cumul thermal times at current date" variablecategory="auxiliary" datatype="DOUBLE" min="-200" max="10000" default="354.582294511779" unit="°C d" inputtype="variable"/>
        <Input name="leafNumber" description="Actual number of phytomers" variablecategory="state" datatype="DOUBLE" min="0" max="25" default=" 4.620511621863958" unit="leaf"  inputtype = "variable"/>
        <Input name="cumulTTFromZC_39" description="cumul of the thermal time ( DeltaTT) since the moment ZC_39" variablecategory="auxiliary" datatype="DOUBLE" min="0" max="10000" default="0" unit="°C d-1"  inputtype = "variable"/>
        <Input name="isMomentRegistredZC_39" description="true if ZC_39 is registered in the calendar" variablecategory="auxiliary" datatype="INT" min="0" max="1" default="0" unit=""  inputtype = "variable"/>
        <Input name="gai" description="used to calculate Terminal spikelet" variablecategory="auxiliary" datatype="DOUBLE" min="0" max="10000" default="0.3255196285135" unit=""  inputtype = "variable"/>
        <Input name="grainCumulTT" description="cumulTT used for the grain developpment" variablecategory="auxiliary" datatype="DOUBLE" min="0" max="10000" default="0" unit="°C d"  inputtype="variable"/>
        <Input name="dayLength" description="length of the day" datatype="DOUBLE" variablecategory="auxiliary" min="0" max="24" unit="h" default="12.7433275303389" inputtype="variable" />
        <Input name="vernaprog" description="progression on a 0  to 1 scale of the vernalization" variablecategory="state" datatype="DOUBLE" min="0" max="10" default = " 1.0532526829571554" unit=""  inputtype="variable"/>
        <Input name="minFinalNumber" description="minimum final leaf number"  variablecategory="state" datatype="DOUBLE" min="0" max="25" default="6.879410413987549" unit="leaf" inputtype="variable" />
        <Input name="fixPhyll" description="Phyllochron with sowing date fix" variablecategory="state" datatype="DOUBLE" min="0" max="10000" default="91.2" unit="°C d"  inputtype="variable"/>
        <Input name="isVernalizable" description="true if the plant is vernalizable" parametercategory="constant" datatype="INT" min="0" max="1" unit="" default="1"  inputtype = "parameter"/>
        <Input name="dse" description="Thermal time from sowing to emergence" parametercategory="species" datatype="DOUBLE" min="0" max="1000" default="105" unit="°C d"  inputtype = "parameter"/>
        <Input name="pFLLAnth" description="Phyllochronic duration of the period between flag leaf ligule appearance and anthesis" parametercategory="constant" datatype="DOUBLE" min="0" max="1000" unit=""  default="2.22" inputtype = "parameter"/>
        <Input name="dcd" description="Duration of the endosperm cell division phase" parametercategory="species" datatype="DOUBLE" min="0" max="10000" default="100" unit="°C d"  inputtype = "parameter"/>
        <Input name="dgf" description="Grain filling duration (from anthesis to physiological maturity)" parametercategory="species" datatype="DOUBLE" min="0" max="10000" default="450" unit="°C d"  inputtype = "parameter"/>
        <Input name="degfm" description="Grain maturation duration (from physiological maturity to harvest ripeness)" parametercategory="species" datatype="DOUBLE" min="0" max="50" default="0" unit="°C d"  inputtype = "parameter"/>
        <Input name="maxDL" description="Saturating photoperiod above which final leaf number is not influenced by daylength" datatype="DOUBLE" min="0" max="24" default="15" unit="h"  inputtype = "parameter"/>
        <Input name="sLDL" description="Daylength response of leaf production" datatype="DOUBLE" min="0" max="1" default="0.85" unit="leaf h-1"  inputtype = "parameter"/>
        <Input name="ignoreGrainMaturation" description="true to ignore grain maturation" datatype="BOOLEAN" default="FALSE" unit=""  inputtype = "parameter"/>
        <Input name="pHEADANTH" description="Number of phyllochron between heading and anthesiss" datatype="DOUBLE" min="0" max="1000" default="1" unit=""  inputtype = "parameter"/>
        <Input name="choosePhyllUse" description="Switch to choose the type of phyllochron calculation to be used" datatype="STRING"  unit="" default="Default"  inputtype = "parameter"/>
        <Input name="p" description="Phyllochron (Varietal parameter)" parametercategory="species" datatype="DOUBLE" min="0" max="1000" default="120" unit="°C d leaf-1"  inputtype = "parameter"/>
        <Input name="phase" description=" the name of the phase" variablecategory="state" datatype="DOUBLE" min="0" max="7" default = "1" unit=""  inputtype="variable"/>
        <Input name="cumulTTFromZC_91" description="cumul of the thermal time (DeltaTT) since the moment ZC_91" variablecategory="auxiliary" datatype="DOUBLE" min="0" max="5000" default = "0" unit="°C d-1" inputtype="variable" />
        <Input name="phyllochron" description="Phyllochron" variablecategory="state" datatype="DOUBLE" min="0" max="1000" default="91.2" unit="°C d leaf-1"  inputtype = "variable"/>
        <Input name="hasLastPrimordiumAppeared" description="if Last Primordium has Appeared" variablecategory="state" datatype="INT" min="0" max="1" default="0" unit=""  inputtype="variable"/>
        <Input name="finalLeafNumber" description="final leaf number" variablecategory="state" datatype="DOUBLE" min="0" max="25" default="0" unit="leaf"  />
      
    </Inputs>
    <Outputs>
        <Output name="finalLeafNumber" description="final leaf number" variablecategory="state" datatype="DOUBLE" min="0" max="25" unit="leaf" />
        <Output name="phase" description="the name of the phase" variablecategory="state" datatype="DOUBLE" min="0" max="7" unit="" />
        <Output name="hasLastPrimordiumAppeared" description="if Last Primordium has Appeared" variablecategory="state"  datatype="INT" min="0" max="1"  unit="" />
   	
    </Outputs>
	<Algorithm  language="Python" platform="" filename="algo/py/UpdatePhase.py" />
	<Algorithm  language="C#" platform="" filename="algo/cs/UpdatePhase.cs" />
	<Algorithm  language="Java" platform="" filename="algo/java/UpdatePhase.java" />
	<Algorithm  language="C++" platform="" filename="algo/cpp/UpdatePhase.cpp" />
	<Algorithm  language="Fortran" platform="" filename="algo/f90/UpdatePhase.f90" /> 
    <Algorithm  language="Cyml" platform="" filename="algo/pyx/UpdatePhase.pyx" /> 
    <Algorithm  language="R" platform="" filename="algo/r/UpdatePhase.r" />    

     <Parametersets>
        <Parameterset name="wheat" description="some values in there" >
        	<Param name="choosePhyllUse">"Default"</Param>
        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="check model1" parameterset = "wheat" description="some values in there">
        	<Test name ="test_wheat1">
        		<InputValue name="phase">1</InputValue>
        		<InputValue name="hasLastPrimordiumAppeared">0</InputValue> 		
				<OutputValue name="phase" precision="1" >2</OutputValue>
				<OutputValue name="hasLastPrimordiumAppeared" >1</OutputValue>
				<OutputValue name="finalLeafNumber" precision ="2">8.80</OutputValue>
       	
        	</Test>
        </Testset>
     
      </Testsets>
 
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/Example_Sirius_CanopyTemperatureMaize.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelUnit.dtd">
<ModelUnit modelid="1" name="CanopyTemperatureMaize" timestep="1" version="1.0">
    <Description>
        <Title>CanopyTemperatureMaize Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>absolutely non</Reference>
        <Abstract>Calculate Energy Balance </Abstract>
    </Description>
    <Inputs>

        <Input name="hourlyTemp" description="" parametercategory="species" datatype="DOUBLE" default="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 5.0, 6.0, 7.0, 7.0, 7.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 2.0, 2.0, 1.0]" min="0" max="1000" unit="°C" uri="some url" inputtype="variable"/>
        <Input name="hourlyVPDair" description="" parametercategory="species" datatype="DOUBLE" default="[0.09,0.08,0.07,0.07,0.07,0.07,0.06,0.06,0.1,0.1,0.2,0.3,0.4,0.4,0.4,0.4,0.3,0.2,0.2,0.1,0.1,0.1,0.1,0.1]" min="0" max="1000" unit="°C" uri="some url" inputtype="variable"/>
        <Input name="hourlySolarRadiation" description="" parametercategory="species" datatype="DOUBLE" default="[0,0,0,0,0,0,0,0,0.1,0.5,1.0,1.4,1.4,1.0,0.5,0.08,0,0,0,0,0,0,0,0]" min="0" max="1000" unit="MJ/m²d" uri="some url" inputtype="variable"/>
        <Input name="wc3cm" description="" parametercategory="species" datatype="DOUBLE" default="2.19" min="0" max="1000" unit="g/m²d" uri="some url" inputtype="variable"/>
        <Input name="Ntip" description="" parametercategory="species" datatype="DOUBLE" default="0" min="0" max="1000" unit=" " uri="some url" inputtype="variable"/>
        <Input name="SwitchMaize" description="true if maize false if wheat" parametercategory="species" datatype="DOUBLE" default="1" min="0" max="1" unit="" uri="some url" inputtype="parameter"/>
  
     
    </Inputs>
    <Outputs>

        <Output name="hourlyCanopyTemperature" description=" " datatype="DOUBLE" min="0" max="5"  unit="°C" uri="some url"/>
 
    </Outputs>
    
    <Algorithm language="C#" platform=""><![CDATA[
 
        if (SwitchMaize == 1)
        	{
        		double A, B, C, D, E;
        		if (Ntip <= 8)
        			{ A = 6.49; B = 0.77; C = 0.01; D = -0.48; E = -0.22; }
        		else
            		{ A = 1.18; B = 1; C = 0.01; D = -1.65; E = 0; } 
       			for (int i = 0; i < 24; i++)
            		{
            			hourlyCanopyTemperature[i] = A + B * hourlyTemp[i] + C * hourlyVPDair[i] + D * hourlySolarRadiation[i] + E * wc3cm;
            		} 
            }        
        
                
      ]]>
     </Algorithm>    
    
    <Algorithm language="python_ext" platform=""><![CDATA[
    
   		hourlyCanopyTemperature = range(24)
     
        if (SwitchMaize == 1):
        	{
        		if (Ntip <= 8):
        			{ 
        				A = 6.49
        				B = 0.77
        				C = 0.01
        				D = -0.48
        				E = -0.22; 
        			}
        		else:
            		{ 
            			A = 1.18
            			B = 1
            		 	C = 0.01
            		 	D = -1.65
            		 	E = 0
            		} 
       			for i in range(0,24):
            		{
            			hourlyCanopyTemperature[i] = A + B * hourlyTemp[i] + C * hourlyVPDair[i] + D * hourlySolarRadiation[i] + E * wc3cm;
            		} 
            }  

      ]]>
     </Algorithm>
    <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        	<Param name="SwitchMaize">1</Param>
  
        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="hourlyTemp">[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 5.0, 6.0, 7.0, 7.0, 7.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 2.0, 2.0, 1.0]</InputValue>
        		<InputValue name="hourlyVPDair">[0.09,0.08,0.07,0.07,0.07,0.07,0.06,0.06,0.1,0.1,0.2,0.3,0.4,0.4,0.4,0.4,0.3,0.2,0.2,0.1,0.1,0.1,0.1,0.1]</InputValue>
        		<InputValue name="hourlySolarRadiation">[0,0,0,0,0,0,0,0,0.1,0.5,1.0,1.4,1.4,1.0,0.5,0.08,0,0,0,0,0,0,0,0]</InputValue>
        		<InputValue name="wc3cm">2.19</InputValue>
        		<InputValue name="Ntip">0</InputValue>
        		<OutputValue name="hourlyCanopyTemperature" precision ="1">[6.8,6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 7.5, 8.1, 9.4, 10.0, 10.7, 10.9, 11.2, 11.4, 10.6, 9.9, 9.1, 8.3, 7.5, 7.5, 7.5, 6.8]</OutputValue>
	
        	</Test>

        </Testset>
      </Testsets>
 	
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/transpiler/snow_pkg/crop2ml/unit.SnowWet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="STICS.Snow.SnowWet" name="SnowWet" timestep="1" version="1.0">
	<Description>
		<Title>water in liquid state in the snow cover calculation</Title>
		<Authors>STICS</Authors>
		<Institution>INRA</Institution>
		<Reference>-</Reference>
		<Abstract>-</Abstract>
	</Description>
	<Inputs>
		<Input name="Swet_t1" description="water in liquid state in the snow cover" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="100.0" unit="mm" uri=""/>
		<Input name="precip" description="current precipitation" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" default="0.0" min="0.0" max="5000.0" unit="mm" uri=""/>
		<Input name="Snowaccu" description=" snowfall accumulation" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="" max="" unit="mm" uri=""/>
		<Input name="Mrf" description="liquid water in the snow cover in the process of refreezing" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="" max="" unit="mm" uri=""/>
		<Input name="M" description="snow in the process of melting" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="" max="" unit="mm" uri=""/>
    </Inputs>
	<Outputs>
		<Output name="Swet" description="water in liquid state in the snow cover" variablecategory="state" datatype="DOUBLE" min="0.0" max="500.0" unit="mm" uri=""/>
	</Outputs>
	<Algorithm language="Cyml" platform="" filename="algo/pyx/SnowWet.pyx" />
	<Parametersets>
		<Parameterset name="paramerSet1" description="set Parameters for TempMax unit" >
		</Parameterset>
	</Parametersets>
	<Testsets>
        <Testset name="check snow model" parameterset = "paramerSet1" description="some values in there" >
        	<Test name ="test_snow1">
                <InputValue name="M">91.2</InputValue>
                <InputValue name="Mrf">91.2</InputValue>
                <InputValue name="Snowaccu">91.2</InputValue>
        		<InputValue name="precip">91.2</InputValue>
				<InputValue name="Swet_t1">0.279</InputValue> 
			    <OutputValue name="Swet" precision ="2">45.6</OutputValue>
        	</Test>
        </Testset>
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/transpiler/snow_pkg/crop2ml/unit.SnowDensity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="STICS.Snow.SnowDensity" name="SnowDensity" timestep="1" version="1.0">
	<Description>
		<Title>Density of snow cover calculation</Title>
		<Authors>STICS</Authors>
		<Institution>INRA</Institution>
		<Reference>-</Reference>
		<Abstract>-</Abstract>
	</Description>
	<Inputs>
		<Input name="ps_t1" description="density of snow cover in previous day" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="100.0" unit="kg m-3" uri=""/>
		<Input name="Sdepth_t1" description="snow cover depth Calculation in previous day" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="5000.0" unit="m" uri=""/>
		<Input name="Sdry_t1" description="water in solid state in the snow cover in previous day" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="500.0" unit="mm" uri=""/>
		<Input name="Swet_t1" description="water in liquid state in the snow cover" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="100.0" unit="mm" uri=""/>
    </Inputs>
	<Outputs>
		<Output name="ps" description="density of snow cover" variablecategory="state" datatype="DOUBLE" min="0.0" max="500.0" unit="kg m-3" uri=""/>
	</Outputs>
	<Algorithm language="Cyml" platform="" filename="algo/pyx/SnowDensity.pyx" />
	<Parametersets>
		<Parameterset name="paramerSet1" description="set Parameters for TempMax unit" >
		</Parameterset>
	</Parametersets>
	<Testsets>
        <Testset name="check snow model" parameterset = "paramerSet1" description="some values in there" >
        	<Test name ="test_snow1">
                <InputValue name="Sdry_t1">91.2</InputValue>
                <InputValue name="Swet_t1">91.2</InputValue>
                <InputValue name="Sdepth_t1">91.2</InputValue>
				<InputValue name="ps_t1">0.279</InputValue> 
			    <OutputValue name="ps" precision ="2">45.6</OutputValue>
        	</Test>
        </Testset>
	</Testsets>
</ModelUnit>
