=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/ModelUnit.dtd
<!---->
<!ELEMENT ModelUnit (Description,Inputs?,Outputs?,Initialization?,Function*, Algorithm+,Parametersets,Testsets)>
<!ATTLIST ModelUnit
  name CDATA #REQUIRED
  modelid CDATA #REQUIRED
  timestep CDATA #IMPLIED
  version CDATA #REQUIRED>

<!ELEMENT Description (Title,Authors,Institution,URI?,Reference?,Abstract)>
<!ATTLIST Description>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED
  platform CDATA #IMPLIED
  filename CDATA #IMPLIED
  function CDATA #IMPLIED>

<!ELEMENT Parametersets (Parameterset+)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset+)>
<!ATTLIST Testsets>

<!ELEMENT Function (#PCDATA)>
<!ATTLIST Function
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED
	type (internal|external) #REQUIRED
	description CDATA #IMPLIED>

<!ELEMENT Initialization (#PCDATA)>
<!ATTLIST Initialization
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED>	

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Authors (#PCDATA)>
<!ATTLIST Authors>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT Abstract (#PCDATA)>
<!ATTLIST Abstract>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  default CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  inputtype (variable|parameter) #REQUIRED
  parametercategory (constant|species|genotypic|soil|private) #IMPLIED
  variablecategory (state|rate|auxillary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Output EMPTY>
<!ATTLIST Output
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  max CDATA #REQUIRED
  min CDATA #REQUIRED
  variablecategory (state|rate|auxiliary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test+)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (InputValue*, OutputValue+)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT InputValue (#PCDATA) >
<!ATTLIST InputValue name CDATA #REQUIRED >

<!ELEMENT OutputValue (#PCDATA) >
<!ATTLIST OutputValue name CDATA #REQUIRED >
<!ATTLIST OutputValue description CDATA #IMPLIED >
<!ATTLIST OutputValue precision CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/phenology/crop2ml/function.Fibonacci.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="crop2ml.fibonacci" name="fibonacci" timestep="1" version="1.0">
    <Description>
        <Title>fibonacci function</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference> to write in package</Reference>
        <Abstract>see documentation</Abstract>
    </Description>
    <Inputs>
        <Input name="n" description="argument"  datatype="INT" inputtype = "variable"/>         
    </Inputs>
    <Outputs>
        <Output name="result" description=" fibonacci number " datatype="INT"/>
    	
    </Outputs>
    
	<Algorithm  language="Python" platform="" filename="algo/py/Fibonacci.py" />
	<Algorithm  language="C#" platform="" filename="algo/cs/Fibonacci.cs" />
	<Algorithm  language="Java" platform="" filename="algo/java/Fibonacci.java" />
	<Algorithm  language="C++" platform="" filename="algo/cpp/Fibonacci.cpp" />
	<Algorithm  language="Fortran" platform="" filename="algo/f90/Fibonacci.f90" />
    <Algorithm  language="Cyml" platform="" filename="algo/pyx/Fibonacci.pyx" />
    <Algorithm  language="R" platform="" filename="algo/r/Fibonacci.r" />

    <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        </Parameterset>
     </Parametersets>
     <Testsets>
        <Testset name="testset1" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
 				<InputValue name="n">6</InputValue>
				<OutputValue name="result">8</OutputValue>
        	</Test>
        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/old_model/Example_Sirius_SoilEvaporation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelUnit.dtd">
<ModelUnit modelid="1" name="SoilEvaporation" timestep="1" version="1.0">
    <Description>
        <Title>SoilEvaporation Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>absolutely non</Reference>
        <Abstract>Calculate Energy Balance </Abstract>
    </Description>
    <Inputs>

        <Input name="diffusionLimitedEvaporation" description="" parametercategory="species" datatype="DOUBLE" default="6605.505" min="0" max="10000" unit="g/m²d" uri="some url" inputtype="variable"/>
        <Input name="energyLimitedEvaporation" description="" parametercategory="species" datatype="DOUBLE" default="448.240" min="0" max="1000" unit="g/m²d" uri="some url" inputtype="variable"/>
     
    </Inputs>
    <Outputs>

        <Output name="soilEvaporation" description=" " datatype="DOUBLE" min="0" max="5"  unit="g/m²d" uri="some url"/>
	
    </Outputs>
    
    <Algorithm language="C#" platform=""><![CDATA[
        soilEvaporation = Math.Min(diffusionLimitedEvaporation, energyLimitedEvaporation);
               
      ]]>
     </Algorithm>    
    
    <Algorithm language="python_ext" platform=""><![CDATA[
           soilEvaporation = min(diffusionLimitedEvaporation, energyLimitedEvaporation)
 

      ]]>
     </Algorithm>
    <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="diffusionLimitedEvaporation">6605.505</InputValue>
        		<InputValue name="energyLimitedEvaporation">448.240</InputValue>
        		
 				<OutputValue name="soilEvaporation" precision ="3">448.240</OutputValue>
	
        	</Test>

        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SiriusComponent/phenology/original/crop2ml/unit.LeafNumber.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Crop2ML.original.LeafNumber" name="LeafNumber" timestep="1" version="001">
    <Description>
        <Title>LeafNumber model</Title>
        <Authors>Pierre MARTRE</Authors>
        <Institution>INRA Montpellier</Institution>
        <URI></URI>
        <Reference>(&apos;&apos;,)</Reference>
        <ExtendedDescription>calculate leaf number. LeafNumber increase is caped at one more leaf per day</ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="deltaTT" description="Thermal time increase of the day" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="100.0" min="0.0" default="0.0" unit="Â°C d"/>
        <Input name="phyllochron_t1" description="phyllochron" inputtype="variable" variablecategory="state" datatype="DOUBLE" max="1000" min="0" default="0" unit="Â°C d leaf-1"/>
        <Input name="hasFlagLeafLiguleAppeared" description="true if flag leaf has appeared (leafnumber reached finalLeafNumber)" inputtype="variable" variablecategory="state" datatype="INT" max="1" min="0" default="1" unit=""/>
        <Input name="leafNumber_t1" description="Actual number of phytomers" inputtype="variable" variablecategory="state" datatype="DOUBLE" max="25" min="0" default="0" unit="leaf"/>
        <Input name="phase" description=" the name of the phase" inputtype="variable" variablecategory="state" datatype="DOUBLE" max="7" min="0" default="1" unit=""/></Inputs>
    <Outputs>
        <Output name="leafNumber" description="Actual number of phytomers" datatype="DOUBLE" variablecategory="state" max="25" min="0" unit="leaf"/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/LeafNumber.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/transpiler/snow_pkg/crop2ml/unit.Melting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="STICS.Snow.Melting" name="Melting" timestep="1" version="1.0">
	<Description>
		<Title>snow in the process of melting</Title>
		<Authors>STICS</Authors>
		<Institution>INRA</Institution>
		<Reference>-</Reference>
		<Abstract>-</Abstract>
	</Description>
	<Inputs>
		<Input name="jul" description="current day of year for the calculation" inputtype="variable" variablecategory="auxiliary" datatype="INT" default="0" min="0" max="366" unit="d" uri=""/>
		<Input name="P_Tmf" description="threshold temperature for snow melting " inputtype="parameter" parametercategory="constant" datatype="DOUBLE" default="0.0" min="0.0" max="5000.0" unit="째C" uri=""/>
		<Input name="P_DKmax" description="difference between the maximum and the minimum melting rates" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" default="0.0" min="0.0" max="5000.0" unit="mm 째C-1 d-1" uri=""/>
		<Input name="P_Kmin" description="minimum melting rate on 21 December" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" default="0.0" min="0.0" max="5000.0" unit="mm 째C-1 d-1" uri=""/>
		<Input name="tavg" description="average temperature" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="100.0" unit="째C" uri=""/>
    </Inputs>
	<Outputs>
		<Output name="M" description="snow in the process of melting" variablecategory="auxiliary" datatype="DOUBLE" min="0.0" max="500.0" unit="mm d-1" uri=""/>
	</Outputs>
	<Algorithm language="Cyml" platform="" filename="algo/pyx/Melting.pyx" />
	<Parametersets>
		<Parameterset name="paramerterSet1" description="set Parameters for TempMax unit" >
            <Param name="P_Tmf">70.0</Param>
            <Param name="P_DKmax">70.0</Param>
            <Param name="P_Kmin">70.0</Param>
		</Parameterset>
	</Parametersets>
	<Testsets>
        <Testset name="check snow model" parameterset = "paramerterSet1" description="some values in there" >
        	<Test name ="test_snow1">
                <InputValue name="tavg">0.279</InputValue>
                <InputValue name="jul">0.279</InputValue>
			    <OutputValue name="Mrf" precision ="2">45.6</OutputValue>
        	</Test>
        </Testset>
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SiriusComponent/sq_energybalance_generated/crop2ml/unit.CanopyTemperature.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Crop2ML.SQ_Energy_Balance.CanopyTemperature" name="CanopyTemperature" timestep="1" version="001">
    <Description>
        <Title>CanopyTemperature model</Title>
        <Authors>Peter D. Jamieson, Glen S. Francis, Derick R. Wilson, Robert J. Martin</Authors>
        <Institution>New Zealand Institute for Crop and Food Research Ltd., New Zealand Institute for Crop and Food Research Ltd., New Zealand Institute for Crop and Food Research Ltd., New Zealand Institute for Crop and Food Research Ltd. </Institution>
        <URI></URI>
        <Reference></Reference>
        <ExtendedDescription>It is calculated from the crop heat flux and the boundary layer conductance </ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="minTair" description="minimum air temperature" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="45" min="-30" default="0.7" unit="Â°C"/>
        <Input name="maxTair" description="maximum air Temperature" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="45" min="-30" default="7.2" unit="Â°C"/>
        <Input name="cropHeatFlux" description=" crop Heat Flux" inputtype="variable" variablecategory="rate" datatype="DOUBLE" max="10000" min="0" default="" unit="g m-2 d-1"/>
        <Input name="conductance" description="the boundary layer conductance" inputtype="variable" variablecategory="state" datatype="DOUBLE" max="10000" min="0" default="" unit="m/d"/>
        <Input name="lambdaV" description="latent heat of vaporization of water" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="10" min="0" default="2.454" unit="MJ/kg"/>
        <Input name="rhoDensityAir" description="Density of air" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="1.225" min="1.225" default="1.225" unit="kg/m**3"/>
        <Input name="specificHeatCapacityAir" description="Specific heat capacity of dry air" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="0.00101" min="0.00101" default="0.00101" unit="MJ/kg/degC"/></Inputs>
    <Outputs>
        <Output name="minCanopyTemperature" description="minimal Canopy Temperature  " datatype="DOUBLE" variablecategory="state" max="45" min="-30" unit="degC"/>
        <Output name="maxCanopyTemperature" description="maximal Canopy Temperature " datatype="DOUBLE" variablecategory="state" max="45" min="-30" unit="degC"/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/CanopyTemperature.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/openalea/SQ_Energy_Balance/crop2ml/unit.NetRadiation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="SQ.EnergyBalance.NetRadiation" name="NetRadiation" timestep="1" version="1.0">
    <Description>
        <Title>NetRadiation Model</Title>
        <Authors>Peter D. Jamieson, Glen S. Francis, Derick R. Wilson, Robert J. Martin</Authors>
        <Institution>New Zealand Institute for Crop and Food Research Ltd.,</Institution>
        <URI></URI>
        <Reference>https://doi.org/10.1016/0168-1923</Reference>
        <ExtendedDescription></ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="minTair" description="minimum air temperature" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="45" min="-30" default="0.7" unit=""/>
        <Input name="maxTair" description="maximum air Temperature" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="45" min="-30" default="7.2" unit=""/>
        <Input name="albedoCoefficient" description="albedo Coefficient" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="1" min="0" default="0.23" unit=""/>
        <Input name="stefanBoltzman" description="stefan Boltzman constant" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="1" min="0" default="4.903E-09" unit=""/>
        <Input name="elevation" description="elevation" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="10000" min="-500" default="0" unit="m"/>
        <Input name="solarRadiation" description="solar Radiation" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="1000" min="0" default="3" unit="MJ m-2 d-1"/>
        <Input name="vaporPressure" description="vapor Pressure" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="1000" min="0" default="6.1" unit="hPa"/>
        <Input name="extraSolarRadiation" description="extra Solar Radiation" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="1000" min="0" default="11.7" unit="MJ m2 d-1"/></Inputs>
    <Outputs>
        <Output name="netRadiation" description="net radiation " datatype="DOUBLE" variablecategory="auxiliary" max="5000" min="0" unit="MJ m-2 d-1"/>
        <Output name="netOutGoingLongWaveRadiation" description="net OutGoing Long Wave Radiation " datatype="DOUBLE" variablecategory="auxiliary" max="5000" min="0" unit="g m-2 d-1"/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/NetRadiation.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/Example_Sirius_VPDairLeaf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/cyrillemidingoyi/PyCropML/render_csharp/test/data/ModelUnit.dtd">
<ModelUnit modelid="1" name="VPDairleaf" timestep="1" version="1.0">
    <Description>
        <Title>VPDairleaf Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>absolutely non</Reference>
        <Abstract>Calculate Energy Balance </Abstract>
    </Description>
    <Inputs>

        <Input name="hourlyTemp" description="" parametercategory="species" datatype="DOUBLE" default="[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 5.0, 6.0, 7.0, 7.0, 7.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 2.0, 2.0, 1.0]" min="0" max="1000" unit="°C" uri="some url" inputtype="variable"/>
        <Input name="hourlyCanopyTemperature" description="" parametercategory="species" datatype="DOUBLE" default="[6.8,6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 7.5, 8.1, 9.4, 10.0, 10.7, 10.9, 11.2, 11.4, 10.6, 9.9, 9.1, 8.3, 7.5, 7.5, 7.5, 6.8]" min="0" max="100" unit="°C" uri="some url" inputtype="variable"/>
        <Input name="RH" description="Relative humidity"  datatype="DOUBLE" default="[86.0, 87.0, 88.0, 88.0, 89.0, 89.0, 89.0, 89.0, 83.0, 74.0, 67.0, 62.0, 59.0, 57.0, 57.0, 59.0, 63.0, 68.0, 73.0, 77.0, 80.0, 82.0, 84.0, 85.0]" min="0" max="100" unit="%" uri="some url" inputtype="variable"/>
        <Input name="SwitchMaize" description="true if maize false if wheat" parametercategory="species" datatype="DOUBLE" default="0" min="0" max="1" unit="" uri="some url" inputtype="parameter"/>
 
   
    </Inputs>
    <Outputs>

        <Output name="hourlyVPDairLeaf" description=" " datatype="DOUBLE" min="0" max="5"  unit="MJ/m²d" uri="some url"/>

    </Outputs>
    
    <Algorithm language="C#" platform=""><![CDATA[

        if (SwitchMaize == 1)
        	{
             		
            	for (int i = 0; i < 24; i++)
        			{
        				hourlyVPDairLeaf[i] = 0.6106 * (Math.Exp((17.27 * hourlyCanopyTemperature[i]) / (hourlyCanopyTemperature[i] + 237.3)) - RH[i] / 100 * Math.Exp((17.27 * hourlyTemp[i]) / (hourlyTemp[i] + 237.3)));
            		}
                   
             }        
    
                
      ]]>
     </Algorithm>
    
    <Algorithm language="python_ext" platform=""><![CDATA[
    
    hourlyVPDairLeaf = range(24)
             
             if (SwitchMaize == 1):
        	{
             		
            	for i in range(0,24):
        			{
        				hourlyVPDairLeaf[i] = 0.6106 * (exp((17.27 * hourlyCanopyTemperature[i]) / (hourlyCanopyTemperature[i] + 237.3)) - RH[i] / 100 * exp((17.27 * hourlyTemp[i]) / (hourlyTemp[i] + 237.3)));
            		}
                   
             } 
     

      ]]>
     </Algorithm>
     <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        	<Param name="SwitchMaize">1</Param>
  
        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="hourlyTemp">[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 5.0, 6.0, 7.0, 7.0, 7.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 2.0, 2.0, 1.0]</InputValue>
        		<InputValue name="hourlyCanopyTemperature">[6.8,6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 6.8, 7.5, 8.1, 9.4, 10.0, 10.7, 10.9, 11.2, 11.4, 10.6, 9.9, 9.1, 8.3, 7.5, 7.5, 7.5, 6.8]</InputValue>
        		<InputValue name="RH">[86.0, 87.0, 88.0, 88.0, 89.0, 89.0, 89.0, 89.0, 83.0, 74.0, 67.0, 62.0, 59.0, 57.0, 57.0, 59.0, 63.0, 68.0, 73.0, 77.0, 80.0, 82.0, 84.0, 85.0]</InputValue>
        		<OutputValue name="hourlyVPDairLeaf" precision ="1">[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5, 0.5, 0.6, 0.6, 0.7, 0.7, 0.8, 0.8, 0.7, 0.6, 0.6, 0.5, 0.5, 0.5, 0.4, 0.4]</OutputValue>
	
        	</Test>

        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SiriusComponent/phenology/original/crop2ml/unit.IsMomentRegistredZC_39.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Crop2ML.original.IsMomentRegistredZC_39" name="IsMomentRegistredZC_39" timestep="1" version="001">
    <Description>
        <Title>IsMomentRegistredZC_39 model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <URI></URI>
        <Reference>(&apos;&apos;,)</Reference>
        <ExtendedDescription>if FlagLeafLiguleJustVisible is already Registred </ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="calendarMoments_t1" description="List containing appearance of each stage" inputtype="variable" variablecategory="state" datatype="STRINGLIST" max="" min="" default="" unit=""/></Inputs>
    <Outputs>
        <Output name="isMomentRegistredZC_39" description=" if Flag leaf ligule has already appeared " datatype="INT" variablecategory="state" max="1" min="0" unit=""/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/IsMomentRegistredZC_39.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>
