=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/ModelUnit.dtd
<!---->
<!ELEMENT ModelUnit (Description,Inputs?,Outputs?,Initialization?,Function*, Algorithm+,Parametersets,Testsets)>
<!ATTLIST ModelUnit
  name CDATA #REQUIRED
  modelid CDATA #REQUIRED
  timestep CDATA #IMPLIED
  version CDATA #REQUIRED>

<!ELEMENT Description (Title,Authors,Institution,URI?,Reference?,Abstract)>
<!ATTLIST Description>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED
  platform CDATA #IMPLIED
  filename CDATA #IMPLIED
  function CDATA #IMPLIED>

<!ELEMENT Parametersets (Parameterset+)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset+)>
<!ATTLIST Testsets>

<!ELEMENT Function (#PCDATA)>
<!ATTLIST Function
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED
	type (internal|external) #REQUIRED
	description CDATA #IMPLIED>

<!ELEMENT Initialization (#PCDATA)>
<!ATTLIST Initialization
	name CDATA #REQUIRED
	language CDATA #REQUIRED
	filename CDATA #IMPLIED>	

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Authors (#PCDATA)>
<!ATTLIST Authors>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT Abstract (#PCDATA)>
<!ATTLIST Abstract>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  default CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  inputtype (variable|parameter) #REQUIRED
  parametercategory (constant|species|genotypic|soil|private) #IMPLIED
  variablecategory (state|rate|auxillary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Output EMPTY>
<!ATTLIST Output
  name NMTOKEN #REQUIRED
  datatype (STRING|DATE|DOUBLE|LIST|STRINGARRAY|DOUBLEARRAY|INTARRAY|STRINGLIST|INTLIST|DOUBLELIST|INT|BOOLEAN|BOOLEANARRAY|BOOLEANLIST|DATELIST|DATEARRAY) #REQUIRED 
  description CDATA #REQUIRED
  max CDATA #REQUIRED
  min CDATA #REQUIRED
  variablecategory (state|rate|auxiliary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test+)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (InputValue*, OutputValue+)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT InputValue (#PCDATA) >
<!ATTLIST InputValue name CDATA #REQUIRED >

<!ELEMENT OutputValue (#PCDATA) >
<!ATTLIST OutputValue name CDATA #REQUIRED >
<!ATTLIST OutputValue description CDATA #IMPLIED >
<!ATTLIST OutputValue precision CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/csharp/examples/pheno_pkg/crop2ml/unit.Phyllochron.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="SQ.pheno_pkg.Phyllochron" name="Phyllochron" timestep="1" version="1.0">
	<Description>
		<Title>Phyllochron Model</Title>
		<Authors>Pierre Martre</Authors>
		<Institution>INRA Montpellier</Institution>
		<Reference>Modeling development phase in the 
                Wheat Simulation Model SiriusQuality.
                See documentation at http://www1.clermont.inra.fr/siriusquality/?page_id=427</Reference>
		<Abstract>Calculate different types of phyllochron </Abstract>
	</Description>
	<Inputs>
		<Input name="fixPhyll" description="Sowing date corrected Phyllochron" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" default="5.0" min="0.0" max="10000.0" unit="°C d leaf-1" uri="some url"/>
		<Input name="leafNumber" description="Actual number of phytomers" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="25.0" unit="leaf" uri="some url"/>
		<Input name="lincr" description="Leaf number above which the phyllochron is increased by Pincr" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="8.0" min="0.0" max="30.0" unit="leaf" uri="some url"/>
		<Input name="ldecr" description="Leaf number up to which the phyllochron is decreased by Pdecr" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="0.0" min="0.0" max="100.0" unit="leaf" uri="some url"/>
		<Input name="pdecr" description="Factor decreasing the phyllochron for leaf number less than Ldecr" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="0.4" min="0.0" max="10.0" unit="-" uri="some url"/>
		<Input name="pincr" description="Factor increasing the phyllochron for leaf number higher than Lincr" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="1.5" min="0.0" max="10.0" unit="-" uri="some url"/>
		<Input name="ptq" description="Photothermal quotient " inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="10000.0" unit="MJ °C-1 d-1 m-2)" uri="some url"/>
		<Input name="gAImean" description="Green Area Index" inputtype="variable" variablecategory="state" datatype="DOUBLE" default="0.0" min="0.0" max="10000.0" unit="m2 m-2" uri="some url"/>
		<Input name="kl" description="Exctinction Coefficient" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="0.45" min="0.0" max="50.0" unit="-" uri="some url"/>
		<Input name="pTQhf" description="Slope to intercept ratio for Phyllochron  parametrization with PhotoThermal Quotient" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="°C d leaf-1" uri="some url"/>
		<Input name="B" description="Phyllochron at PTQ equal 1" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="20.0" min="0.0" max="1000.0" unit="°C d leaf-1" uri="some url"/>
		<Input name="p" description="Phyllochron (Varietal parameter)" inputtype="parameter" parametercategory="species" datatype="DOUBLE" default="120.0" min="0.0" max="1000.0" unit="°C d leaf-1" uri="some url"/>
		<Input name="choosePhyllUse" description="Switch to choose the type of phyllochron calculation to be used" inputtype="parameter" parametercategory="species" datatype="STRING" default="Default" min="" max="" unit="-" uri="some url"/>
		<Input name="areaSL" description=" Area Leaf" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="cm2" uri="some url"/>
		<Input name="areaSS" description="Area Sheath" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="cm2" uri="some url"/>
		<Input name="lARmin" description="LAR minimum" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="leaf-1 °C" uri="some url"/>
		<Input name="lARmax" description="LAR maximum" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="leaf-1 °C" uri="some url"/>
		<Input name="sowingDensity" description="Sowing Density" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="plant m-2" uri="some url"/>
		<Input name="lNeff" description="Leaf Number efficace" inputtype="parameter" parametercategory="genotypic" datatype="DOUBLE" default="0.0" min="0.0" max="1000.0" unit="leaf" uri="some url"/>
	</Inputs>
	<Outputs>
		<Output name="phyllochron" description=" the rate of leaf appearance " variablecategory="state" datatype="DOUBLE" min="0" max="1000" unit=" °C d leaf-1" uri="some url"/>
	</Outputs>
    <Algorithm  language="Cyml" platform="" filename="algo/pyx/PhyllochronModule.pyx"/>
    <Parametersets>
        <Parameterset name="wheat" description="some values in there" >
        	<Param name="lincr">8.0</Param>
        	<Param name="ldecr">3.0</Param>
        	<Param name="pdecr">0.4</Param>
            <Param name="pincr">1.25</Param>
            <Param name="ptq">0.97</Param>
            <Param name="kl">0.45</Param> 
            <Param name="p">120.0</Param> 
            <Param name="choosePhyllUse">"Default"</Param>              
        </Parameterset>
     </Parametersets>
     <Testsets>
        <Testset name="check wheat model" parameterset = "wheat" description="some values in there" >
        	<Test name ="test_wheat1">
        		<InputValue name="fixPhyll">91.2</InputValue>       						
			    <OutputValue name="phyllochron" precision ="2">36.48</OutputValue>							
        	</Test>
        </Testset>
      </Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SimplaceComponent/SoilTemp/crop2ml/unit.STMPsimCalculator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Simplace.SoilTemp.STMPsimCalculator" name="STMPsimCalculator" timestep="1" version="001">
    <Description>
        <Title>STMPsimCalculator model</Title>
        <Authors>Gunther Krauss</Authors>
        <Institution>INRES Pflanzenbau, Uni Bonn</Institution>
        <URI>http://www.simplace.net/doc/simplace_modules/</URI>
        <Reference>(&apos;http://www.simplace.net/doc/simplace_modules/&apos;,)</Reference>
        <ExtendedDescription>as given in the documentation</ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="cSoilLayerDepth" description="Depth of soil layer" inputtype="parameter" parametercategory="constant" datatype="DOUBLEARRAY" len="" max="20.0" min="0.03" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/metre"/>
        <Input name="cFirstDayMeanTemp" description="Mean temperature on first day" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="50.0" min="-40.0" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/degree_Celsius"/>
        <Input name="cAVT" description="Constant Temperature of deepest soil layer" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="20.0" min="-10.0" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/degree_Celsius"/>
        <Input name="cABD" description="Mean bulk density" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="4.0" min="1.0" default="2.0" unit="http://www.wurvoc.org/vocabularies/om-1.8/tonne_per_cubic_metre"/>
        <Input name="cDampingDepth" description="Initial value for damping depth of soil" inputtype="parameter" parametercategory="constant" datatype="DOUBLE" max="20.0" min="1.5" default="6.0" unit="http://www.wurvoc.org/vocabularies/om-1.8/metre"/>
        <Input name="iSoilWaterContent" description="Content of water in Soil" inputtype="variable" variablecategory="exogenous" datatype="DOUBLE" max="20.0" min="1.5" default="5.0" unit="http://www.wurvoc.org/vocabularies/om-1.8/millimetre"/>
        <Input name="iSoilSurfaceTemperature" description="Temperature at soil surface" inputtype="variable" variablecategory="exogenous" datatype="DOUBLE" max="20.0" min="1.5" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/degree_Celsius"/>
        <Input name="SoilTempArray" description="Array of temperature " inputtype="variable" variablecategory="state" datatype="DOUBLEARRAY" len="" max="40" min="-20" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/degree_Celsius"/>
        <Input name="pSoilLayerDepth" description="Depth of soil layer plus additional depth" inputtype="variable" variablecategory="state" datatype="DOUBLEARRAY" len="" max="20.0" min="0.03" default="" unit="http://www.wurvoc.org/vocabularies/om-1.8/metre"/></Inputs>
    <Outputs>
        <Output name="SoilTempArray" description="Array of temperature " datatype="DOUBLEARRAY" variablecategory="state" len="" max="40" min="-20" unit="http://www.wurvoc.org/vocabularies/om-1.8/degree_Celsius"/></Outputs>
    <Initialization name="init" language="cyml" filename="algo/pyx/init.STMPsimCalculator.pyx"/>
    <Algorithm language="cyml" platform="" filename="algo/pyx/STMPsimCalculator.pyx"/>
    <Parametersets>
        <Parameterset name="pset1" description="first parametersets">
            <Param name="cSoilLayerDepth">[0.1, 0.5, 1.5]</Param>
            <Param name="cFirstDayMeanTemp">15.0</Param>
            <Param name="cAVT">9.0</Param>
            <Param name="cABD">1.4</Param>
            <Param name="cDampingDepth">6.0</Param></Parameterset></Parametersets>
    <Testsets>
        <Testset name="testset1" parameterset="pset1" description="first testset">
            <Test name="test1">
                <InputValue name="iSoilWaterContent">0.3</InputValue>
                <InputValue name="iSoilSurfaceTemperature">6.0</InputValue>
                <OutputValue name="SoilTempArray" precision="5">[13.624360856350041, 13.399968504634286, 12.599999999999845, 12.2, 11.4, 10.6, 9.799999999999999, 9.0]</OutputValue></Test></Testset></Testsets></ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/Example_Sirius_PriestlyTaylor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelUnit.dtd">
<ModelUnit modelid="1" name="PriestlyTaylor" timestep="1" version="1.0">
    <Description>
        <Title>evapoTranspirationPriestlyTaylor  Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <Reference>absolutely non</Reference>
        <Abstract>Calculate Energy Balance </Abstract>
    </Description>
    <Inputs>
        <Input name="netRadiationEquivalentEvaporation" description="" parametercategory="species" datatype="DOUBLE" default="638.142" min="0" max="1000" unit="g/m²d" uri="some url" inputtype="variable"/>
        <Input name="hslope" description="" parametercategory="species" datatype="DOUBLE" default="0.584" min="0" max="1000" unit="hPa/°C" uri="some url" inputtype="variable"/>
        <Input name="psychrometricConstant" description="psychrometric constant" parametercategory="species" datatype="DOUBLE" default="0.66" min="0" max="1" unit="" uri="some url" inputtype="parameter"/>
        <Input name="Alpha" description="Priestley-Taylor evapotranspiration proportionality constant" parametercategory="species" datatype="DOUBLE" default="1.5" min="0" max="100" unit="" uri="some url" inputtype="parameter"/>
   </Inputs>
   
    <Outputs>
         <Output name="evapoTranspirationPriestlyTaylor" description=" " datatype="DOUBLE" min="0" max="5"  unit="Cd/leaf" uri="some url"/>
   	
    </Outputs>
    
    <Algorithm language="C#" platform=""><![CDATA[
    
        evapoTranspirationPriestlyTaylor = Math.Max((Alpha * hslope * (netRadiationEquivalentEvaporation) / (hslope + psychrometricConstant)), 0);
     
                
      ]]>
     </Algorithm>    
    
    <Algorithm language="python_ext" platform=""><![CDATA[
           evapoTranspirationPriestlyTaylor = max((Alpha * hslope * (netRadiationEquivalentEvaporation) / (hslope + psychrometricConstant)), 0)
    
    

      ]]>
     </Algorithm>
      <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        	<Param name="Alpha">1.5</Param>

        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="netRadiationEquivalentEvaporation">638.142</InputValue>
				<OutputValue name="evapoTranspirationPriestlyTaylor" precision ="3">449.367</OutputValue>
	
        	</Test>

        </Testset>
      </Testsets>
 	
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/Models/energybalance_pkg/crop2ml/unit.SoilHeatFlux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="SQ.EnergyBalance.SoilHeatFlux" name="SoilHeatFlux" timestep="1" version="1.0">
    <Description>
        <Title>SoilHeatFlux Model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA/LEPSE Montpellier</Institution>
        <Reference>Modelling energy balance in the wheat crop model SiriusQuality2:
            Evapotranspiration and canopy and soil temperature calculations</Reference>
        <Abstract>The available energy in the soil </Abstract>
    </Description>
    <Inputs>
        <Input name="netRadiationEquivalentEvaporation" variablecategory="state" description="net Radiation Equivalent Evaporation"  datatype="DOUBLE" default="638.142" min="0" max="5000" unit="g m-2 d-1" uri="http://www1.clermont.inra.fr/siriusquality/?page_id=547" inputtype="variable"/>
        <Input name="tau" description="plant cover factor" parametercategory="species" datatype="DOUBLE" default="0.9983" min="0" max="100" unit="" uri="http://www1.clermont.inra.fr/siriusquality/?page_id=547" inputtype="parameter"/>
        <Input name="soilEvaporation" description="soil Evaporation" variablecategory="state"  datatype="DOUBLE" default="448.240" min="0" max="10000" unit="g m-2 d-1" uri="http://www1.clermont.inra.fr/siriusquality/?page_id=547" inputtype="variable"/>
    </Inputs>

    <Outputs>
        <Output name="soilHeatFlux" description="soil Heat Flux " variablecategory="rate"  datatype="DOUBLE" min="0" max="10000"  unit="g m-2 d-1" uri="http://www1.clermont.inra.fr/siriusquality/?page_id=547"/>
   	</Outputs>

    <Algorithm  language="Cyml" platform="" filename="algo/pyx/soilheatflux.pyx" />


    <Parametersets>
        <Parameterset name="set1" description="some values in there" >
        	<Param name="tau">0.9983</Param>

        </Parameterset>

     </Parametersets>
     <Testsets>
        <Testset name="first" parameterset = "set1" description="some values in there" >
        	<Test name ="test1">
        		<InputValue name="netRadiationEquivalentEvaporation">638.142</InputValue>
        		<InputValue name="soilEvaporation">448.240</InputValue>
 				<OutputValue name="soilHeatFlux" precision ="3">188.817</OutputValue>

        	</Test>

        </Testset>
      </Testsets>



</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/exo/Example_Bioma_GrowingDegreeDaysTemperature.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/cyrillemidingoyi/PyCropML/render_csharp/test/data/ModelUnit.dtd">
<ModelUnit modelid="GrowingDegreeDaysTemperature" timestep="1" name="Example" version="1">
	<Description>
		<Title>GrowingDegreeDaysTemperature</Title>
		<Authors>various</Authors>
		<Institution>JRC - CREA</Institution>
		<URI></URI>
		<Abstract><![CDATA[ Growing degree days based on temperature, 
					Confalonieri,R., Gusberti, D., Acutis, M., 2006]]></Abstract>
	</Description>
	<Inputs>
		<Input name="BaseTemperatureDevelopment" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="-10" max="40" default="10" unit="°C" description="Base temperature for development" />
		<Input name="CutoffTemperatureDevelopment" datatype="DOUBLE" inputtype="parameter" parametercategory="constant" min="10" max="50" default="40" unit="°C" description="Cutoff temperature for development" />		
		<Input name="AirTemperatureAverage" datatype="DOUBLE" inputtype="variable" min="-30" max="55" default="25" unit="°C" description="Daily average air temperature"/>		
		<Input name="GrowingDegreeDaysTemperature" datatype="DOUBLE" inputtype="variable" min="0" max="8000" default="100" unit="°C" description="Potential growing degree days calculated on temperature"/>		

	</Inputs>
	<Outputs>
		<Output name="GrowingDegreeDaysTemperature" datatype="DOUBLE" min="0" max="8000"  unit="°C" description="Potential growing degree days calculated on temperature"/>
		<Output name="GrowingDegreeDaysTemperatureRate" datatype="DOUBLE" min="0" max="50"  unit="°C" description="Potential daily rate of growing degree days accumulation based on temperature"/>		
	</Outputs>
	<Algorithm language="C#" platform = ""><![CDATA[ 
				double Tavg = AirTemperatureAverage;

                if (Tavg <= BaseTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = 0;
                }
                else if (Tavg >= CutoffTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = CutoffTemperatureDevelopment - BaseTemperatureDevelopment;
                }
                else
                {
                    GrowingDegreeDaysTemperatureRate = Tavg - BaseTemperatureDevelopment;
                }
				GrowingDegreeDaysTemperature = GrowingDegreeDaysTemperature + GrowingDegreeDaysTemperatureRate;
		]]>
	</Algorithm>
	
	<Algorithm language="Java" platform = ""><![CDATA[ 
				double Tavg = AirTemperatureAverage;

                if (Tavg <= BaseTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = 0;
                }
                else if (Tavg >= CutoffTemperatureDevelopment)
                {
                    GrowingDegreeDaysTemperatureRate = CutoffTemperatureDevelopment - BaseTemperatureDevelopment;
                }
                else
                {
                    GrowingDegreeDaysTemperatureRate = Tavg - BaseTemperatureDevelopment;
                }
				GrowingDegreeDaysTemperature = GrowingDegreeDaysTemperature + GrowingDegreeDaysTemperatureRate;
		]]>
	</Algorithm>
	<Algorithm language="python_ext" platform=" ">
		<![CDATA[ 
				Tavg = float(AirTemperatureAverage)

                if (Tavg <= BaseTemperatureDevelopment):
                {
                    GrowingDegreeDaysTemperatureRate = 0
                }
                elif (Tavg >= CutoffTemperatureDevelopment):
                {
                    GrowingDegreeDaysTemperatureRate = CutoffTemperatureDevelopment - BaseTemperatureDevelopment
                }
                else:
                {
                    GrowingDegreeDaysTemperatureRate = Tavg - BaseTemperatureDevelopment
                }
				GrowingDegreeDaysTemperature = GrowingDegreeDaysTemperature + GrowingDegreeDaysTemperatureRate
		]]>
	</Algorithm>
	
	<Parametersets>
		<Parameterset name="default" description="default values">
			<Param name="BaseTemperatureDevelopment">10</Param>
			<Param name="CutoffTemperatureDevelopment">40</Param>			
		</Parameterset>		
	</Parametersets>
	<Testsets>
		<Testset name="check 1" parameterset="default" description="some test values">
			<Test name="check 1 1">
				<InputValue name="AirTemperatureAverage">16</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature" precision = "3">11.0</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate" precision = "3">6.0</OutputValue>
			</Test>
			<Test name="check 1 2">
				<InputValue name="AirTemperatureAverage">46</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature" precision = "3">35.0</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate" precision = "3">30.0</OutputValue>
			</Test>
			<Test name="check 1 3">
				<InputValue name="AirTemperatureAverage">-1</InputValue>
				<InputValue name="GrowingDegreeDaysTemperature">5</InputValue>
				<OutputValue name="GrowingDegreeDaysTemperature" precision = "3">5.0</OutputValue>
				<OutputValue name="GrowingDegreeDaysTemperatureRate " precision = "3">0.0</OutputValue>
			</Test>
		</Testset>		
	</Testsets>
</ModelUnit>

=== AgriculturalModelExchangeInitiative/PyCrop2ML/src/pycropml/transpiler/antlr_py/tests/examples/SiriusComponent/phenology/original/crop2ml/unit.UpdateCalendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelUnit.dtd">
<ModelUnit modelid="Crop2ML.original.UpdateCalendar" name="UpdateCalendar" timestep="1" version="001">
    <Description>
        <Title>UpdateCalendar model</Title>
        <Authors>Pierre Martre</Authors>
        <Institution>INRA Montpellier</Institution>
        <URI></URI>
        <Reference>(&apos;&apos;,)</Reference>
        <ExtendedDescription>Lists containing for each stage the date it occurs as well as a copy of all types of cumulated thermal times </ExtendedDescription>
        <ShortDescription></ShortDescription></Description>
    <Inputs>
        <Input name="calendarCumuls" description="list containing for each stage occured its cumulated thermal times" inputtype="variable" variablecategory="state" datatype="DOUBLELIST" max="" min="" default="" unit="Â°C d"/>
        <Input name="calendarMoments" description="List containing appearance of each stage" inputtype="variable" variablecategory="state" datatype="STRINGLIST" max="" min="" default="" unit=""/>
        <Input name="cumulTT" description="cumul thermal times at currentdate" inputtype="variable" variablecategory="auxiliary" datatype="DOUBLE" max="10000" min="-200" default="112.330110409888" unit="Â°C d"/>
        <Input name="calendarDates" description="List containing  the dates of the wheat developmental phases" inputtype="variable" variablecategory="state" datatype="DATELIST" max="" min="" default="" unit=""/>
        <Input name="phase" description=" the name of the phase" inputtype="variable" variablecategory="state" datatype="DOUBLE" max="7" min="0" default="1" unit=""/>
        <Input name="currentdate" description="current date " inputtype="variable" variablecategory="auxiliary" datatype="DATE" max="" min="" default="" unit=""/></Inputs>
    <Outputs>
        <Output name="calendarCumuls" description="list containing for each stage occured its cumulated thermal times" datatype="DOUBLELIST" variablecategory="state" max="" min="" unit="Â°C d"/>
        <Output name="calendarMoments" description="List containing appearance of each stage" datatype="STRINGLIST" variablecategory="state" max="" min="" unit=""/>
        <Output name="calendarDates" description="List containing  the dates of the wheat developmental phases" datatype="DATELIST" variablecategory="state" max="" min="" unit=""/></Outputs>
    <Algorithm language="cyml" platform="" filename="algo/pyx/UpdateCalendar.pyx"/>
    <Parametersets/>
    <Testsets/></ModelUnit>
