=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/java/ModelUnit.dtd
<!ELEMENT ModelUnit (Description,Inputs?,Outputs?,Algorithm,Parametersets,
                     Testsets)>
<!ATTLIST ModelUnit>

<!ELEMENT Description (Title,Author,Institution,URI?,Reference?,Abstract)>
<!ATTLIST Description>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED>

<!ELEMENT Parametersets (Parameterset+)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset+)>
<!ATTLIST Testsets>

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Author (#PCDATA)>
<!ATTLIST Author>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT Abstract (#PCDATA)>
<!ATTLIST Abstract>

<!ELEMENT Input (param)*>
<!ATTLIST Input
  datatype NMTOKEN #REQUIRED
  default CDATA #IMPLIED
  description CDATA #REQUIRED
  max CDATA #REQUIRED
  min CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  type NMTOKEN #REQUIRED
  unit CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Output (Param)*>
<!ATTLIST Output
  datatype (CHAR|CHARARRAY|DATE|DOUBLE|DOUBLEARRAY|INT|INTARRAY|BOOLEAN) #REQUIRED 
  description CDATA #REQUIRED
  max CDATA #REQUIRED
  min CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  unit CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test*)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (Param*, Check*)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT Check (#PCDATA) >
<!ATTLIST Check name CDATA #REQUIRED >
<!ATTLIST Check description CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/PyCrop2ML/test/data/java/STMPsimCalculator.unit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ModelUnit PUBLIC "-//SIMPLACE/DTD SOL 1.0//EN" "http://simplace.net/dtd/ModelUnit.dtd">
<ModelUnit>
	<Description>
		<Title>STMPsimCalculator</Title>
		<Author>Andreas Enders</Author>
		<Institution>Crop Science Group Bonn</Institution>
		<URI>http://www.simplace.net/doc/simplace_modules/class_net.simplace.sim.components.soil.temperature.STMPsimCalculator.html</URI>
		<Abstract>Calculates the soil temperature in n layers depending on climate and soil conditions.</Abstract>
	</Description>
	<Algorithm language="java">
		if (firstcall)
		{
			Double[] Z = cSoilLayerDepth;
			Double firstDayMeanTemp = cFirstDayMeanTemp;
			Double[] _profiledepth = Z[Z.length - 1];
			Double additionalDepth = cDampingDepth - _profiledepth;
			Double firstAdditionalLayerHight = additionalDepth - floor(additionalDepth);
			Integer layers = (int)(abs(ceil(additionalDepth)))+Z.length;
			Double[] SoilTempArray = new Double[layers];
			Double[] tz = new Double[layers];
			for (int i = 0; i &lt; SoilTempArray.length; i++)
			{
				double depth;
				if (i &lt; Z.length)
					depth = Z[i];
				else //first additional layer might be smaller than 1 m
					depth = _profiledepth + firstAdditionalLayerHight + i - Z.length;
				tz[i] = depth;
				SoilTempArray[i] = (firstDayMeanTemp * (cDampingDepth - depth) + cAVT * depth) /
				cDampingDepth; //set linear aproximation to the soil temperature as
				initial value
			}
			_z = tz;
		}
		double XLAG =.8; //XLAG = LAG = Coefficient for weighting
		yesterday's soil temperature
		double XLG1 = 1 - XLAG; //XLG1 = Inverse
		of coefficient for weighting yesterday's soil temperature
		double DP = (1 + 2.5 * cABD / (cABD + exp(6.53 -5.63 * cABD))); //DP= Maximum damping depth (m)
		double WC = 0.001*iSoilWaterContent/((.356 -.144 * cABD) * _profiledepth); //WC seems to be a water content related
		factor [cm3/g] to modify the damping depth ?
		double DD = exp(log(0.5/DP)*((1 - WC)/(1 + WC)) * 2) * DP; 
		// DD(t)= Damping depth (m), multiplied by 2 (20110628 TG) to increase damping depth
		// DD could be also calculated from d = (2Dh /w )^0.5 (easy soilT, Nofziger et al.), where w = 2Pi/365 (d^-1)
		//and Dh is the thermal diffusivity (m^2 s^-l) with ( Dh= K/Cs, Cs = volumetric heat capacity in J m^-3 K^-1, K=??)

		double Z1 = 0; //Z1=Depth of the bottom of the previous soil layer, initialized with 0 (m)
		for (int i = 0; i &lt; SoilTempArray.length; i++)
		{
			double ZD = 0.5*(Z1 + _z[i])/DD;
			//Factor of the depth in soil: Middle of depth of layer divided by damping depth
			double RATE = ZD / (ZD + exp(-.8669 - 2.0775 * ZD)) * (cAVT - iSoilSurfaceTemperature);	//RATE = Rate of change of STMP(ISL) (Â°C)
			SoilTempArray[i] = XLAG * SoilTempArray[i] + XLG1 * (RATE + iSoilSurfaceTemperature);
			Z1 = _z[i];
		}
	</Algorithm>
	<Parametersets>
		<Parameterset name="cold" description="some values for cold weather">
			<Param name="cSoilLayerDepth">{0.1,0.2,0.4,0.6,0.9,1.1,1.3,1.5,1.7,1.9,2.1,2.3}</Param>
			<Param name="cFirstDayMeanTemp">10</Param>
			<Param name="cAVT">10</Param>
			<Param name="cABD">3.12</Param>
			<Param name="cDampingDepth">5.75</Param>
		</Parameterset>
		<Parameterset name="hot" description="some values in there">
			<Param name="cSoilLayerDepth">{0.1,0.2,0.4,0.6,0.9,1.1,1.3,1.5,1.7,1.9,2.1,2.3}</Param>
			<Param name="cFirstDayMeanTemp">10</Param>
			<Param name="cAVT">10</Param>
			<Param name="cABD">3.12</Param>
			<Param name="cDampingDepth">5.75</Param>
		</Parameterset>
		<Parameterset name="dry" description="some values in there">
			<Param name="cSoilLayerDepth">{0.1,0.2,0.4,0.6,0.9,1.1,1.3,1.5,1.7,1.9,2.1,2.3}</Param>
			<Param name="cFirstDayMeanTemp">10</Param>
			<Param name="cAVT">10</Param>
			<Param name="cABD">3.12</Param>
			<Param name="cDampingDepth">5.75</Param>
			<Param name="cFirstDayMeanTemp">0.12</Param>
		</Parameterset>
	</Parametersets>
	<Testsets>
		<Testset name="check soil temp" parameterset="cold" description="some values in there">
			<Test name="cold_and_colder">
				<Param name="iSoilWaterContent">0.22</Param>
				<Param name="iSoilSurfaceTemperature">-0.75</Param>
				<Check name="SoilTempArray">{-2,-1.2,-0.6,-0,1.2,2.8,4.4,6.8,8.6,9.6,10,10}</Check>
			</Test>
		</Testset>
		<Testset name="check soil temp" parameterset="hot" description="some values in there">
			<Test name="hot_and_hotter">
				<Param name="iSoilWaterContent">0.22</Param>
				<Param name="iSoilSurfaceTemperature">29.75</Param>
				<Check name="SoilTempArray">{-2,-1.2,-0.6,-0,1.2,2.8,4.4,6.8,8.6,9.6,10,10}</Check>
			</Test>
		</Testset>
		<Testset name="check soil temp" parameterset="dry" description="some values in there">
			<Test name="dry_test">
				<Param name="iSoilWaterContent">0.12</Param>
				<Param name="iSoilSurfaceTemperature">20.75</Param>
				<Check name="SoilTempArray">{-2,-1.2,-0.6,-0,1.2,2.8,4.4,6.8,8.6,9.6,10,10}</Check>
			</Test>
		</Testset>
	</Testsets>
</ModelUnit>
